import { LINKS } from "../lib/site";
import { Mark } from "./Mark";

const COLUMNS: { title: string; links: { label: string; href: string }[] }[] = [
  {
    title: "Product",
    links: [
      { label: "Web demo", href: LINKS.app },
      { label: "macOS", href: LINKS.macosDmg },
      { label: "Windows", href: LINKS.windowsZip },
      { label: "Roadmap", href: LINKS.roadmap },
    ],
  },
  {
    title: "Community",
    links: [
      { label: "GitHub", href: LINKS.github },
      { label: "Feedback", href: LINKS.feedback },
      { label: "Back the project", href: LINKS.polar },
    ],
  },
  {
    title: "Build",
    links: [
      { label: "Docs", href: LINKS.docs },
      { label: "MCP setup", href: LINKS.docsMcp },
      { label: "Agents & MCP", href: "#open-layer" },
    ],
  },
];

export default function Footer() {
  return (
    <footer className="border-t border-border/60">
      <div className="mx-auto max-w-6xl px-4 py-14">
        <div className="flex flex-col justify-between gap-10 md:flex-row">
          <div className="max-w-xs">
            <Mark withWordmark size={26} />
            <p className="mt-4 text-sm leading-relaxed text-muted-foreground">
              The open canvas layer. Open source end to end, BYOK always.
            </p>
          </div>
          <nav className="grid grid-cols-2 gap-10 sm:grid-cols-3">
            {COLUMNS.map((col) => (
              <div key={col.title}>
                <p className="font-mono text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">
                  {col.title}
                </p>
                <ul className="mt-3 space-y-2.5">
                  {col.links.map((link) => (
                    <li key={link.label}>
                      <a
                        href={link.href}
                        className="text-sm text-foreground/80 transition-colors hover:text-foreground"
                        {...(link.href.startsWith("http")
                          ? { target: "_blank", rel: "noopener noreferrer" }
                          : {})}
                      >
                        {link.label}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </nav>
        </div>
        <div className="mt-12 flex flex-col items-start justify-between gap-3 border-t border-border/60 pt-6 sm:flex-row sm:items-center">
          <p className="text-xs text-muted-foreground">© 2026 Joaquin Terrasa</p>
          <p className="font-mono text-[11px] text-muted-foreground">
            every frame on this page was generated by calca
          </p>
        </div>
      </div>
    </footer>
  );
}
