import { FiArrowDown } from "react-icons/fi";

import { appLink } from "../lib/site";

interface FormatTile {
  src: string;
  alt: string;
  format: string;
  prompt: string;
  preset: "uiux" | "marketing" | "brand" | "presentation";
  span: string;
}

const TILES: FormatTile[] = [
  {
    src: "/gallery/web-bakery.png",
    alt: "Landing page for a sourdough bakery generated by calca",
    format: "Web page",
    prompt:
      "A landing page for a sourdough bakery — warm hero with a tagline, a three-item bread menu with prices, a short story section, and a footer with hours and address.",
    preset: "marketing",
    span: "md:col-span-7",
  },
  {
    src: "/gallery/dashboard-fleet.png",
    alt: "Fleet-tracking dashboard UI generated by calca",
    format: "App UI",
    prompt:
      "A fleet-tracking dashboard with a dark sidebar, four KPI cards, a route-status table, and a small map panel.",
    preset: "uiux",
    span: "md:col-span-5",
  },
  {
    src: "/gallery/brand-launch.png",
    alt: "Launch announcement card generated by calca",
    format: "Brand card",
    prompt:
      "A 1200x628 launch announcement card for a minimal note-taking app called Jot — bold headline, one screenshot mockup, release date.",
    preset: "brand",
    span: "md:col-span-5",
  },
  {
    src: "/gallery/deck-robotics.png",
    alt: "Pitch-deck cover slide generated by calca",
    format: "Deck slide",
    prompt:
      "A pitch-deck cover slide for a warehouse-robotics startup — big title, one-line thesis, team row, and a contact footer.",
    preset: "presentation",
    span: "md:col-span-7",
  },
];

function Tile({ tile }: { tile: FormatTile }) {
  return (
    <a
      href={appLink({ prompt: tile.prompt, preset: tile.preset, format: tile.format })}
      className={`group flex flex-col overflow-hidden rounded-2xl border border-border/70 bg-card transition-transform duration-200 ease-out hover:-translate-y-1 ${tile.span}`}
    >
      <div className="overflow-hidden border-b border-border/60">
        <img
          src={tile.src}
          alt={tile.alt}
          loading="lazy"
          className="block w-full transition-transform duration-300 ease-out group-hover:scale-[1.015]"
        />
      </div>
      <div className="flex flex-col gap-2 p-4">
        <span className="inline-flex w-fit items-center gap-1.5 rounded-full bg-secondary px-2.5 py-1 font-mono text-[11px] font-medium uppercase tracking-[0.12em] text-secondary-foreground">
          <span className="inline-block h-1.5 w-1.5 rounded-[2px] bg-primary" />
          {tile.format}
        </span>
        <p className="line-clamp-3 font-mono text-[13px] leading-relaxed text-muted-foreground">
          “{tile.prompt}”
        </p>
      </div>
    </a>
  );
}

export default function Formats() {
  return (
    <section id="formats" className="mx-auto max-w-6xl px-4 py-24">
      <div className="reveal max-w-2xl">
        <h2 className="font-display text-4xl font-bold leading-[1.02] tracking-[-0.02em] sm:text-5xl">
          If you can describe it,
          <br />
          it fits on the canvas.
        </h2>
        <p className="mt-5 text-lg leading-relaxed text-muted-foreground">
          One prompt in, live variations out. Pages, prototypes, decks, brand boards, social cards,
          and the formats nobody has named yet.
        </p>
      </div>

      <div className="reveal mt-12 grid grid-cols-1 gap-5 md:grid-cols-12">
        {TILES.map((tile) => (
          <Tile key={tile.src} tile={tile} />
        ))}
      </div>

      <div className="reveal mt-5 grid grid-cols-1 gap-5 md:grid-cols-12">
        <div className="flex flex-col justify-center rounded-2xl border border-dashed border-border bg-transparent p-6 md:col-span-5">
          <p className="font-display text-xl font-semibold">And everything else</p>
          <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
            Docs, wireframes, email templates, moodboards, social assets. The canvas does not care
            about the format. Describe the frame you want and take the take you like.
          </p>
        </div>
        <a
          href="#try"
          className="group flex items-center justify-between rounded-2xl border border-border/70 bg-frame p-6 transition-transform duration-200 ease-out hover:-translate-y-1 md:col-span-7"
        >
          <div>
            <p className="font-display text-xl font-semibold">Real output, not mockups</p>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              Every frame on this page came out of the app you can open right now, prompts included.
            </p>
          </div>
          <span className="ml-6 inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary text-primary-foreground transition-transform duration-200 group-hover:translate-y-1">
            <FiArrowDown className="h-4.5 w-4.5" />
          </span>
        </a>
      </div>
    </section>
  );
}
